sudo: required
language: generic 

services:
  - docker

brefore_install:
  - docker build -t wolvezine24/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wolvezine24/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "docker-react"
        env: "Dockerreact-env"
        bucket_name: "elasticbeanstalk-us-east-1-870450444774"
        bucket_path: "docker-react"
        on:
            branch: master
        aws_access_id: $AWS_ACCESS_KEY
        secret_access_key:
            secret: "$AWS_SECRET_KEY"