version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - "/app/node_modules"
            - .:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - "/app/node_modules"
            - .:/app
        command: ["npm", "run", "test"]
    deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "docker-react"
        env: "Dockerreact-env"
        bucket_name: "elasticbeanstalk-us-east-1-870450444774"
        bucket_path: "docker-react"
        on:
            branch: master
        aws_access_key: $AWS_ACCESS_KEY
        secret_access_key:
            secret: "$AWS_SECRET_KEY"