FROM node:alpine

WORKDIR '/app'

COPY ./package.json .
# To Fix Permissions for Packages
RUN npm config set unsafe-perm true

RUN npm install --force
COPY . /app
RUN chown -R node /app/node_modules
USER node

CMD ["npm", "run", "start"]